"""extend api key prefix to 12 chars

Revision ID: 002
Revises: 001
Create Date: 2026-01-27 15:24:20.382618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Deactivate all existing API keys since their 8-char prefixes won't match the new 12-char format
    # Users will need to regenerate their API keys after this migration
    op.execute("UPDATE api_keys SET is_active = false WHERE is_active = true")
    
    # Extend key_prefix column from 8 to 12 characters
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
